// import './jquery.js'
// import 'modules/admin-lte/plugins/jquery-ui/jquery-ui.min.js'
// import 'modules/admin-lte/plugins/fastclick/fastclick'
// // import 'modules/admin-lte/plugins/slimScroll/jquery.slimscroll.min'
// import 'modules/admin-lte/dist/js/adminlte.min.js'

// import 'modules/@fortawesome/fontawesome-free/css/all.min.css'
// import 'modules/font-awesome/css/font-awesome.min.css'
// import 'modules/ionicons/dist/css/ionicons.min.css'
// // import 'modules/admin-lte/bootstrap/css/bootstrap.min.css'
// import 'modules/admin-lte/dist/css/adminlte.min.css'
// // import 'modules/admin-lte/dist/css/skins/_all-skins.min.css'
// // import 'modules/admin-lte/plugins/iCheck/flat/blue.css'

import './custom.css'